adx_entityname: adx_webpage
adx_isdefault: false
adx_name: Partner Application
adx_pagetemplateid: 9d2f5fdc-045b-e611-80d7-00155db70ed0
adx_rewriteurl: ~
adx_type: 756150001
adx_usewebsiteheaderandfooter: true
adx_webtemplateid: bd0a0c3c-045b-e611-80d7-00155db70ed0
